<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $nationalities = [
            ['id' => 1, 'name' => 'netherlands', 'slug' => 'Amsterdam', 'city_slug' => 'amsterdam', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 2, 'name' => 'belgium', 'slug' => 'Antwerp', 'city_slug' => 'antwerp', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 3, 'name' => 'belgium', 'slug' => 'Brussels', 'city_slug' => 'brussels', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 4, 'name' => 'greece', 'slug' => 'Athens', 'city_slug' => 'athens', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 5, 'name' => 'greece', 'slug' => 'Mykonos', 'city_slug' => 'mykonos', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 6, 'name' => 'azerbaijan', 'slug' => 'Baku', 'city_slug' => 'baku', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 7, 'name' => 'indonesia', 'slug' => 'Bali', 'city_slug' => 'bali', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 8, 'name' => 'thailand', 'slug' => 'Bangkok', 'city_slug' => 'bangkok', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 9, 'name' => 'thailand', 'slug' => 'Pattaya', 'city_slug' => 'pattaya', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 10, 'name' => 'thailand', 'slug' => 'Phuket', 'city_slug' => 'phuket', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 11, 'name' => 'spain', 'slug' => 'Barcelona', 'city_slug' => 'barcelona', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 12, 'name' => 'spain', 'slug' => 'Madrid', 'city_slug' => 'madrid', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 13, 'name' => 'spain', 'slug' => 'Ibiza', 'city_slug' => 'ibiza', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 14, 'name' => 'spain', 'slug' => 'Puerto-Banus', 'city_slug' => 'puerto-banus', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 15, 'name' => 'china', 'slug' => 'Beijing', 'city_slug' => 'beijing', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 16, 'name' => 'china', 'slug' => 'Macau', 'city_slug' => 'macau', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 17, 'name' => 'china', 'slug' => 'Guangdong', 'city_slug' => 'guangdong', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 18, 'name' => 'china', 'slug' => 'Shanghai', 'city_slug' => 'shanghai', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 19, 'name' => 'china', 'slug' => 'Shenzhen', 'city_slug' => 'shenzhen', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 21, 'name' => 'germany', 'slug' => 'Frankfurt', 'city_slug' => 'frankfurt', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 23, 'name' => 'germany', 'slug' => 'Hamburg', 'city_slug' => 'hamburg', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 24, 'name' => 'germany', 'slug' => 'Stuttgart', 'city_slug' => 'stuttgart', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 25, 'name' => 'germany', 'slug' => 'Dortmund', 'city_slug' => 'dortmund', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 26, 'name' => 'germany', 'slug' => 'Essen', 'city_slug' => 'essen', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 27, 'name' => 'germany', 'slug' => 'Dresden', 'city_slug' => 'dresden', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 28, 'name' => 'germany', 'slug' => 'Duisburg', 'city_slug' => 'duisburg', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 30, 'name' => 'germany', 'slug' => 'Nuremberg', 'city_slug' => 'nuremberg', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 31, 'name' => 'germany', 'slug' => 'Hannover', 'city_slug' => 'hannover', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 32, 'name' => 'germany', 'slug' => 'Bochum', 'city_slug' => 'bochum', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 33, 'name' => 'germany', 'slug' => 'Karlsruhe', 'city_slug' => 'karlsruhe', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 34, 'name' => 'germany', 'slug' => 'Mannheim', 'city_slug' => 'mannheim', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 35, 'name' => 'germany', 'slug' => 'Ulm', 'city_slug' => 'ulm', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 36, 'name' => 'germany', 'slug' => 'Wiesi', 'city_slug' => 'wiesi', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 37, 'name' => 'germany', 'slug' => 'Munich', 'city_slug' => 'munich', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 38, 'name' => 'germany', 'slug' => 'Cologne', 'city_slug' => 'cologne', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 41, 'name' => 'colombia', 'slug' => 'Bogata', 'city_slug' => 'bogata', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 42, 'name' => 'united-states', 'slug' => 'Boston', 'city_slug' => 'boston', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 43, 'name' => 'united-states', 'slug' => 'Washington-Dc', 'city_slug' => 'washington-dc', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 44, 'name' => 'united-states', 'slug' => 'Dallas', 'city_slug' => 'dallas', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 45, 'name' => 'united-states', 'slug' => 'Hawaii', 'city_slug' => 'hawaii', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 46, 'name' => 'united-states', 'slug' => 'Houston', 'city_slug' => 'houston', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 47, 'name' => 'united-states', 'slug' => 'Los-Angeles', 'city_slug' => 'los-angeles', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 48, 'name' => 'united-states', 'slug' => 'Las-Vegas', 'city_slug' => 'las-vegas', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 49, 'name' => 'united-states', 'slug' => 'Miami', 'city_slug' => 'miami', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 50, 'name' => 'united-states', 'slug' => 'San-Francisco', 'city_slug' => 'san-francisco', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 51, 'name' => 'united-states', 'slug' => 'San-Diego', 'city_slug' => 'san-diego', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 52, 'name' => 'united-states', 'slug' => 'New-York', 'city_slug' => 'new-york', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 53, 'name' => 'united-states', 'slug' => 'San-Jose', 'city_slug' => 'san-jose', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 54, 'name' => 'united-states', 'slug' => 'Chicago', 'city_slug' => 'chicago', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 55, 'name' => 'bulgaria', 'slug' => 'Sofia', 'city_slug' => 'sofia', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 56, 'name' => 'romania', 'slug' => 'Bucharest', 'city_slug' => 'bucharest', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 57, 'name' => 'hungary', 'slug' => 'Budapest', 'city_slug' => 'budapest', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 58, 'name' => 'egypt', 'slug' => 'Cairo', 'city_slug' => 'cairo', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 59, 'name' => 'france', 'slug' => 'Cannes', 'city_slug' => 'cannes', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 60, 'name' => 'france', 'slug' => 'Courchevel', 'city_slug' => 'courchevel', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 61, 'name' => 'france', 'slug' => 'Paris', 'city_slug' => 'paris', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 62, 'name' => 'saint-tropez', 'slug' => 'Saint Tropez', 'city_slug' => 'saint-tropez', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 63, 'name' => 'south-africa', 'slug' => 'Cape-Town', 'city_slug' => 'cape-town', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 64, 'name' => 'uae', 'slug' => 'Dubai', 'city_slug' => 'dubai', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 65, 'name' => 'ireland', 'slug' => 'Dublin', 'city_slug' => 'dublin', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 66, 'name' => 'croatia', 'slug' => 'Dubrovnik', 'city_slug' => 'dubrovnik', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 67, 'name' => 'italy', 'slug' => 'Florence', 'city_slug' => 'florence', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 68, 'name' => 'italy', 'slug' => 'Milan', 'city_slug' => 'milan', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 69, 'name' => 'italy', 'slug' => 'Porto Carlo', 'city_slug' => 'porto carlo', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 70, 'name' => 'italy', 'slug' => 'Rome', 'city_slug' => 'rome', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 71, 'name' => 'italy', 'slug' => 'Venice', 'city_slug' => 'venice', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 72, 'name' => 'switzerland', 'slug' => 'Geneva', 'city_slug' => 'geneva', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 73, 'name' => 'switzerland', 'slug' => 'Gstaad', 'city_slug' => 'gstaad', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 74, 'name' => 'switzerland', 'slug' => 'Saint Moritz', 'city_slug' => 'saint moritz', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 75, 'name' => 'switzerland', 'slug' => 'Zurich', 'city_slug' => 'zurich', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 76, 'name' => 'switzerland', 'slug' => 'Basel', 'city_slug' => 'basel', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 77, 'name' => 'switzerland', 'slug' => 'Bern', 'city_slug' => 'bern', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 78, 'name' => 'switzerland', 'slug' => 'Zug', 'city_slug' => 'zug', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 79, 'name' => 'switzerland', 'slug' => 'Chur', 'city_slug' => 'chur', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 80, 'name' => 'switzerland', 'slug' => 'Lausanne', 'city_slug' => 'lausanne', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 81, 'name' => 'switzerland', 'slug' => 'Rapperswil', 'city_slug' => 'rapperswil', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 82, 'name' => 'switzerland', 'slug' => 'Uster', 'city_slug' => 'uster', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 83, 'name' => 'switzerland', 'slug' => 'Frauenfeld', 'city_slug' => 'frauenfeld', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 84, 'name' => 'switzerland', 'slug' => 'Emmen', 'city_slug' => 'emmen', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 85, 'name' => 'switzerland', 'slug' => 'Sion', 'city_slug' => 'sion', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 86, 'name' => 'switzerland', 'slug' => 'Luzern', 'city_slug' => 'luzern', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 87, 'name' => 'switzerland', 'slug' => 'Fribourg', 'city_slug' => 'fribourg', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 88, 'name' => 'switzerland', 'slug' => 'Winterthur', 'city_slug' => 'winterthur', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 89, 'name' => 'switzerland', 'slug' => 'Lugano', 'city_slug' => 'lugano', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 90, 'name' => 'switzerland', 'slug' => 'Sankt Gallen', 'city_slug' => 'sankt gallen', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 91, 'name' => 'switzerland', 'slug' => 'Montreux', 'city_slug' => 'montreux', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 92, 'name' => 'switzerland', 'slug' => 'Biel', 'city_slug' => 'biel', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 94, 'name' => 'switzerland', 'slug' => 'Dietikon', 'city_slug' => 'dietikon', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 95, 'name' => 'switzerland', 'slug' => 'Schaffhausen', 'city_slug' => 'schaffhausen', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 96, 'name' => 'switzerland', 'slug' => 'Thun', 'city_slug' => 'thun', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 97, 'name' => 'switzerland', 'slug' => 'Lancy', 'city_slug' => 'lancy', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 98, 'name' => 'switzerland', 'slug' => 'La Chaux-De-Fonds', 'city_slug' => 'la-chaux-de-fonds', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 99, 'name' => 'switzerland', 'slug' => 'Baar', 'city_slug' => 'baar', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 101, 'name' => 'switzerland', 'slug' => 'Yverdon-Les-Bains', 'city_slug' => 'yverdon-les-bains', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 103, 'name' => 'finland', 'slug' => 'Helsinki', 'city_slug' => 'helsinki', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 104, 'name' => 'malaysia', 'slug' => 'Kuala-Lumpur', 'city_slug' => 'kuala-lumpur', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 105, 'name' => 'kuwait', 'slug' => 'Kuwait', 'city_slug' => 'kuwait', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 106, 'name' => 'japan', 'slug' => 'Kyoto', 'city_slug' => 'kyoto', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 107, 'name' => 'japan', 'slug' => 'Tokyo', 'city_slug' => 'tokyo', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 108, 'name' => 'peru', 'slug' => 'Lima', 'city_slug' => 'lima', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 109, 'name' => 'portugal', 'slug' => 'Lisbon', 'city_slug' => 'lisbon', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 110, 'name' => 'slovenia', 'slug' => 'Ljubljana', 'city_slug' => 'ljubljana', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 111, 'name' => 'united-kingdom', 'slug' => 'London', 'city_slug' => 'london', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 112, 'name' => 'luxembourg', 'slug' => 'Luxembourg', 'city_slug' => 'luxembourg', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 113, 'name' => 'malta', 'slug' => 'Malta', 'city_slug' => 'malta', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 114, 'name' => 'malta', 'slug' => 'Valletta', 'city_slug' => 'valletta', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 115, 'name' => 'bahrain', 'slug' => 'Manama', 'city_slug' => 'manama', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 116, 'name' => 'australia', 'slug' => 'Melbourne', 'city_slug' => 'melbourne', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 117, 'name' => 'australia', 'slug' => 'Sydney', 'city_slug' => 'sydney', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 118, 'name' => 'mexico', 'slug' => 'Mexico-City', 'city_slug' => 'mexico-city', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 119, 'name' => 'mexico', 'slug' => 'Tulum', 'city_slug' => 'tulum', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 120, 'name' => 'monaco', 'slug' => 'Monaco', 'city_slug' => 'monaco', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 121, 'name' => 'russia', 'slug' => 'Moscow', 'city_slug' => 'moscow', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 122, 'name' => 'russia', 'slug' => 'Sochi', 'city_slug' => 'sochi', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 123, 'name' => 'russia', 'slug' => 'Saint Petersburg', 'city_slug' => 'saint-petersburg', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 124, 'name' => 'india', 'slug' => 'New-Delhi', 'city_slug' => 'new-delhi', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 125, 'name' => 'norway', 'slug' => 'Oslo', 'city_slug' => 'oslo', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 126, 'name' => 'montenegro', 'slug' => 'Podgorica', 'city_slug' => 'podgorica', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 127, 'name' => 'czech-republic', 'slug' => 'Prague', 'city_slug' => 'prague', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 128, 'name' => 'latvia', 'slug' => 'Riga', 'city_slug' => 'riga', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 129, 'name' => 'brazil', 'slug' => 'Rio-De-Janeiro', 'city_slug' => 'rio-de-janeiro', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 130, 'name' => 'south korea', 'slug' => 'Seoul', 'city_slug' => 'seoul', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 131, 'name' => 'singapore', 'slug' => 'Singapore', 'city_slug' => 'singapore', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 133, 'name' => 'sweden', 'slug' => 'Stockholm', 'city_slug' => 'stockholm', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 134, 'name' => 'taiwan', 'slug' => 'Taipei', 'city_slug' => 'taipei', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 135, 'name' => 'estonia', 'slug' => 'Tallinn', 'city_slug' => 'tallinn', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 136, 'name' => 'canada', 'slug' => 'Toronto', 'city_slug' => 'toronto', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 137, 'name' => 'canada', 'slug' => 'Vancouver', 'city_slug' => 'vancouver', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 138, 'name' => 'austria', 'slug' => 'Vienna', 'city_slug' => 'vienna', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 139, 'name' => 'poland', 'slug' => 'Warsaw', 'city_slug' => 'warsaw', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 140, 'name' => 'new-zealand', 'slug' => 'Wellington', 'city_slug' => 'wellington', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 148, 'name' => 'albania', 'slug' => 'Yerevan', 'city_slug' => 'yerevan', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 149, 'name' => 'austria', 'slug' => 'Salzburg ', 'city_slug' => 'salzburg ', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 150, 'name' => 'belarus', 'slug' => 'Minsk ', 'city_slug' => 'minsk ', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 151, 'name' => 'bosnia-herzegovina', 'slug' => 'Sarajevo', 'city_slug' => 'sarajevo', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 152, 'name' => 'bosnia-herzegovina', 'slug' => 'Sarajevo', 'city_slug' => 'sarajevo', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 153, 'name' => 'croatia', 'slug' => 'Zagreb', 'city_slug' => 'zagreb', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 154, 'name' => 'croatia', 'slug' => 'Split', 'city_slug' => 'split', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 155, 'name' => 'cyprus', 'slug' => 'Limassol', 'city_slug' => 'limassol', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 156, 'name' => 'cyprus', 'slug' => 'Nicosia', 'city_slug' => 'nicosia', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 157, 'name' => 'cyprus', 'slug' => 'Larnaca', 'city_slug' => 'larnaca', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 158, 'name' => 'denmark', 'slug' => 'Copenhagen', 'city_slug' => 'copenhagen', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 159, 'name' => 'france', 'slug' => 'Nice', 'city_slug' => 'nice', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 160, 'name' => 'france', 'slug' => 'Lyon', 'city_slug' => 'lyon', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 161, 'name' => 'france', 'slug' => 'Marseille', 'city_slug' => 'marseille', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 162, 'name' => 'germany', 'slug' => 'Berlin', 'city_slug' => 'berlin', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 163, 'name' => 'germany', 'slug' => 'Düsseldorf', 'city_slug' => 'dusseldorf', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 164, 'name' => 'germany', 'slug' => 'Hannover ', 'city_slug' => 'hannover ', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 165, 'name' => 'greece', 'slug' => 'Thessaloniki', 'city_slug' => 'thessaloniki', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 166, 'name' => 'iceland', 'slug' => 'Reykjavik ', 'city_slug' => 'reykjavik ', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 167, 'name' => 'italy', 'slug' => 'Bologna', 'city_slug' => 'bologna', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 168, 'name' => 'italy', 'slug' => 'Napoli', 'city_slug' => 'napoli', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 169, 'name' => 'italy', 'slug' => 'Bari', 'city_slug' => 'bari', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 170, 'name' => 'italy', 'slug' => 'Torino', 'city_slug' => 'torino', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 171, 'name' => 'italy', 'slug' => 'Vicenza', 'city_slug' => 'vicenza', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 172, 'name' => 'italy', 'slug' => 'Trieste ', 'city_slug' => 'trieste', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 173, 'name' => 'italy', 'slug' => 'Genoa', 'city_slug' => 'genoa', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 174, 'name' => 'italy', 'slug' => 'Parma', 'city_slug' => 'parma', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 175, 'name' => 'italy', 'slug' => 'Treviso', 'city_slug' => 'treviso', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 176, 'name' => 'italy', 'slug' => 'Perugia', 'city_slug' => 'perugia', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 177, 'name' => 'italy', 'slug' => 'Verona', 'city_slug' => 'verona', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 178, 'name' => 'lithuania', 'slug' => 'Vilnius', 'city_slug' => 'vilnius', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 179, 'name' => 'liechtenstein', 'slug' => 'Vaduz', 'city_slug' => 'vaduz', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 180, 'name' => 'malta', 'slug' => 'Saint Julian', 'city_slug' => 'saint-julian', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 181, 'name' => 'malta', 'slug' => 'Sliema', 'city_slug' => 'sliema', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 182, 'name' => 'malta', 'slug' => 'Bugibba', 'city_slug' => 'bugibba', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 183, 'name' => 'malta', 'slug' => 'Gzira', 'city_slug' => 'gzira', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 184, 'name' => 'moldova', 'slug' => 'Kishinev', 'city_slug' => 'kishinev', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 185, 'name' => 'monaco', 'slug' => 'Monte Carlo', 'city_slug' => 'monte-carlo', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 186, 'name' => 'montenegro', 'slug' => 'Budva', 'city_slug' => 'budva', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 187, 'name' => 'netherlands', 'slug' => 'Rotterdam', 'city_slug' => 'rotterdam', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 188, 'name' => 'netherlands', 'slug' => 'Hague', 'city_slug' => 'hague', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 189, 'name' => 'netherlands', 'slug' => 'Schiphol', 'city_slug' => 'schiphol', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 190, 'name' => 'netherlands', 'slug' => 'Utrecht', 'city_slug' => 'utrecht', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 191, 'name' => 'netherlands', 'slug' => 'Leiden', 'city_slug' => 'leiden', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 192, 'name' => 'netherlands', 'slug' => 'Alkmaar', 'city_slug' => 'alkmaar', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 193, 'name' => 'macedonia', 'slug' => 'Skopje ', 'city_slug' => 'skopje ', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 194, 'name' => 'portugal', 'slug' => 'Porto', 'city_slug' => 'porto', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 195, 'name' => 'romania', 'slug' => 'Sibiu', 'city_slug' => 'sibiu', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 196, 'name' => 'romania', 'slug' => 'Brasov', 'city_slug' => 'brasov', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 197, 'name' => 'serbia', 'slug' => 'Belgrade', 'city_slug' => 'belgrade', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 198, 'name' => 'slovakia', 'slug' => 'Bratislava', 'city_slug' => 'bratislava', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 199, 'name' => 'spain', 'slug' => 'Palma de Mallorca', 'city_slug' => 'palma-de-mallorca', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 200, 'name' => 'spain', 'slug' => 'Marbella', 'city_slug' => 'marbella', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 201, 'name' => 'spain', 'slug' => 'Tenerife', 'city_slug' => 'tenerife', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 202, 'name' => 'spain', 'slug' => 'Valencia', 'city_slug' => 'valencia', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 203, 'name' => 'turkey', 'slug' => 'Istanbul', 'city_slug' => 'istanbul', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 204, 'name' => 'turkey', 'slug' => 'Ankara', 'city_slug' => 'ankara', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 205, 'name' => 'turkey', 'slug' => 'Izmir', 'city_slug' => 'izmir', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 206, 'name' => 'turkey', 'slug' => 'Bodrum ', 'city_slug' => 'Bodrum ', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 207, 'name' => 'united-kingdom', 'slug' => 'Manchester', 'city_slug' => 'manchester', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 208, 'name' => 'united-kingdom', 'slug' => 'Birmingham', 'city_slug' => 'birmingham', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 209, 'name' => 'united-kingdom', 'slug' => 'Liverpool', 'city_slug' => 'liverpool', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 210, 'name' => 'united-kingdom', 'slug' => 'Leeds', 'city_slug' => 'leeds', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 211, 'name' => 'australia', 'slug' => 'Perth', 'city_slug' => 'perth', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 212, 'name' => 'australia', 'slug' => 'Brisbane', 'city_slug' => 'brisbane', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 213, 'name' => 'australia', 'slug' => 'Canberra', 'city_slug' => 'canberra', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 214, 'name' => 'australia', 'slug' => 'Adelaide', 'city_slug' => 'adelaide', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 215, 'name' => 'australia', 'slug' => 'Gold Coast', 'city_slug' => 'gold-coast', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 216, 'name' => 'bahrain', 'slug' => 'Juffair ', 'city_slug' => 'juffair ', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 217, 'name' => 'brazil', 'slug' => 'São Paulo', 'city_slug' => 'sao-paulo', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 218, 'name' => 'brazil', 'slug' => 'Brasilia', 'city_slug' => 'brasilia', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 219, 'name' => 'brazil', 'slug' => 'Florianopolis', 'city_slug' => 'florianopolis', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 220, 'name' => 'brazil', 'slug' => 'Recife', 'city_slug' => 'recife', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 221, 'name' => 'canada', 'slug' => 'Montreal', 'city_slug' => 'montreal', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 222, 'name' => 'canada', 'slug' => 'Edmonton', 'city_slug' => 'edmonton', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 223, 'name' => 'canada', 'slug' => 'Ottawa', 'city_slug' => 'ottawa ', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 224, 'name' => 'chile', 'slug' => 'Santiago de Chile', 'city_slug' => 'santiago-de-chile ', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 225, 'name' => 'china', 'slug' => 'Hong Kong', 'city_slug' => 'hong-kong', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 226, 'name' => 'china', 'slug' => 'Guangzhou', 'city_slug' => 'guangzhou', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 227, 'name' => 'china', 'slug' => 'Chengdu', 'city_slug' => 'chengdu', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 228, 'name' => 'colombia', 'slug' => 'Medellin', 'city_slug' => 'medellin', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 229, 'name' => 'colombia', 'slug' => 'Cartagena', 'city_slug' => 'cartagena', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 230, 'name' => 'colombia', 'slug' => 'Cali ', 'city_slug' => 'Cali ', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 231, 'name' => 'costarica', 'slug' => 'San José', 'city_slug' => 'san-jose', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 232, 'name' => 'ecuador', 'slug' => 'Quito', 'city_slug' => 'quito', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 233, 'name' => 'french-polynesia', 'slug' => 'Bora Bora', 'city_slug' => 'bora-bora', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 234, 'name' => 'georgia', 'slug' => 'Tbilisi ', 'city_slug' => 'tbilisi ', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 235, 'name' => 'georgia', 'slug' => 'Batumi', 'city_slug' => 'batumi', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 236, 'name' => 'ghana', 'slug' => 'Accra', 'city_slug' => 'accra', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 237, 'name' => 'guatemala', 'slug' => 'Guatemala', 'city_slug' => 'guatemala', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 238, 'name' => 'india', 'slug' => 'Mumbai', 'city_slug' => 'mumbai', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 239, 'name' => 'india', 'slug' => 'Hyderabad', 'city_slug' => 'hyderabad', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 240, 'name' => 'india', 'slug' => 'Bangalore', 'city_slug' => 'bangalore', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 241, 'name' => 'india', 'slug' => 'Ahmedabad', 'city_slug' => 'ahmedabad', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 242, 'name' => 'india', 'slug' => 'Pune', 'city_slug' => 'pune', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 243, 'name' => 'indonesia', 'slug' => 'Jakarta', 'city_slug' => 'jakarta', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 244, 'name' => 'indonesia', 'slug' => 'Bandung', 'city_slug' => 'bandung', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 245, 'name' => 'indonesia', 'slug' => 'Surabaya', 'city_slug' => 'surabaya', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 246, 'name' => 'israel', 'slug' => 'Tel Aviv', 'city_slug' => 'tel-aviv', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 247, 'name' => 'israel', 'slug' => 'Jerusalem', 'city_slug' => 'jerusalem', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 248, 'name' => 'jamaica', 'slug' => 'Kingston', 'city_slug' => 'kingston', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 249, 'name' => 'jamaica', 'slug' => 'Montego Bay', 'city_slug' => 'montego-bay', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 250, 'name' => 'japan', 'slug' => 'Osaka', 'city_slug' => 'osaka', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 251, 'name' => 'jordan', 'slug' => 'Amman', 'city_slug' => 'amman', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 252, 'name' => 'kazakhstan', 'slug' => 'Astana', 'city_slug' => 'astana', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 253, 'name' => 'kazakhstan', 'slug' => 'Almaty', 'city_slug' => 'almaty', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 254, 'name' => 'kenya', 'slug' => 'Nairobi', 'city_slug' => 'nairobi', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 255, 'name' => 'kuwait', 'slug' => 'Salmiya', 'city_slug' => 'salmiya', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 256, 'name' => 'kuwait', 'slug' => 'Mahboula', 'city_slug' => 'mahboula', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 257, 'name' => 'lebanon', 'slug' => 'Beirut', 'city_slug' => 'beirut', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 258, 'name' => 'lebanon', 'slug' => 'Jounieh', 'city_slug' => 'jounieh', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 259, 'name' => 'lebanon', 'slug' => 'Kaslik', 'city_slug' => 'kaslik', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 260, 'name' => 'mexico', 'slug' => 'Cancun', 'city_slug' => 'Cancun', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 261, 'name' => 'mexico', 'slug' => 'Playa del Carmen', 'city_slug' => 'playa-del-carmen', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 262, 'name' => 'mexico', 'slug' => 'Cabo San Lucas', 'city_slug' => 'cabo-san-lucas', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 263, 'name' => 'mexico', 'slug' => 'Puerto Vallarta', 'city_slug' => 'puerto-vallarta', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 264, 'name' => 'mexico', 'slug' => 'Guadalajara', 'city_slug' => 'guadalajara', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 265, 'name' => 'mexico', 'slug' => 'Tijuana', 'city_slug' => 'tijuana', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 266, 'name' => 'mexico', 'slug' => 'Monterrey', 'city_slug' => 'monterrey', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 267, 'name' => 'morocco', 'slug' => 'Casablanca', 'city_slug' => 'casablanca', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 268, 'name' => 'morocco', 'slug' => 'Marrakech', 'city_slug' => 'marrakech', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 269, 'name' => 'new-zealand', 'slug' => 'Auckland', 'city_slug' => 'auckland', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 270, 'name' => 'nigeria', 'slug' => 'Lagos', 'city_slug' => 'lagos', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 271, 'name' => 'nigeria', 'slug' => 'Abuja', 'city_slug' => 'abuja', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 272, 'name' => 'oman', 'slug' => 'Muscat', 'city_slug' => 'muscat', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 273, 'name' => 'oman', 'slug' => 'Salalah', 'city_slug' => 'salalah', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 274, 'name' => 'pakistan', 'slug' => 'Karachi', 'city_slug' => 'karachi', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 275, 'name' => 'pakistan', 'slug' => 'Lahore', 'city_slug' => 'lahore', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 276, 'name' => 'pakistan', 'slug' => 'Islamabad', 'city_slug' => 'islamabad', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 277, 'name' => 'panama', 'slug' => 'Panama City', 'city_slug' => 'panama-city', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 278, 'name' => 'philippines', 'slug' => 'Makati', 'city_slug' => 'makati', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 279, 'name' => 'philippines', 'slug' => 'Manila', 'city_slug' => 'manila', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 280, 'name' => 'qatar', 'slug' => 'Doha', 'city_slug' => 'doha', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 281, 'name' => 'saudi-arabia', 'slug' => 'Riyadh', 'city_slug' => 'riyadh', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 282, 'name' => 'saudi-arabia', 'slug' => 'Jeddah', 'city_slug' => 'jeddah', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 283, 'name' => 'saudi-arabia', 'slug' => 'Al Khobar', 'city_slug' => 'al-khobar', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 284, 'name' => 'saudi-arabia', 'slug' => 'Dammam', 'city_slug' => 'dammam', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 285, 'name' => 'south africa', 'slug' => 'Johannesburg', 'city_slug' => 'johannesburg', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 286, 'name' => 'sri-lanka', 'slug' => 'Colombo', 'city_slug' => 'colombo', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 287, 'name' => 'tanzania', 'slug' => 'Zanzibar', 'city_slug' => 'zanzibar', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 288, 'name' => 'tunisia', 'slug' => 'Tunis', 'city_slug' => 'tunis', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 289, 'name' => 'uae', 'slug' => 'Abu Dhabi', 'city_slug' => 'abu-dhabi', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 290, 'name' => 'uruguay', 'slug' => 'Montevideo', 'city_slug' => 'montevideo', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 291, 'name' => 'uruguay', 'slug' => 'Punta del Este', 'city_slug' => 'punta-del-este', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 292, 'name' => 'united-states', 'slug' => 'Orlando', 'city_slug' => 'orlando', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 293, 'name' => 'united-states', 'slug' => 'Dallas', 'city_slug' => 'dallas', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 294, 'name' => 'united-states', 'slug' => 'Atlanta', 'city_slug' => 'atlanta', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 295, 'name' => 'united-states', 'slug' => 'Austin', 'city_slug' => 'austin', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 296, 'name' => 'uzbekistan', 'slug' => 'Taskent', 'city_slug' => 'taskent', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 297, 'name' => 'venezuela', 'slug' => 'Caracas', 'city_slug' => 'caracas', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 298, 'name' => 'vietnam', 'slug' => 'Ho Chi Minh Saigon', 'city_slug' => 'ho-chi-minh-saigon ', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 299, 'name' => 'vietnam', 'slug' => 'Hanoi', 'city_slug' => 'hanoi', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 300, 'name' => 'saint-barthelemy', 'slug' => 'Saint Barthelemy', 'city_slug' => 'saint-barthelemy', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 301, 'name' => 'france', 'slug' => 'Courchevel', 'city_slug' => 'courchevel', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 302, 'name' => 'united-states', 'slug' => 'Aspen', 'city_slug' => 'aspen', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 303, 'name' => 'united-states', 'slug' => 'Palm Beach', 'city_slug' => 'palm-beach', 'price' => 500, 'created_at' => NULL, 'updated_at' => NULL],
        ];

        DB::table('nationalities')->insert($nationalities);
    }
}