<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->insert([
            ['id' => 1, 'name' => 'Netherlands', 'slug' => 'netherlands'],
            ['id' => 2, 'name' => 'Belgium', 'slug' => 'belgium'],
            ['id' => 3, 'name' => 'Greece', 'slug' => 'greece'],
            ['id' => 4, 'name' => 'Azerbaijan', 'slug' => 'azerbaijan'],
            ['id' => 5, 'name' => 'Indonesia', 'slug' => 'indonesia'],
            ['id' => 6, 'name' => 'Thailand', 'slug' => 'thailand'],
            ['id' => 7, 'name' => 'Spain', 'slug' => 'spain'],
            ['id' => 8, 'name' => 'China', 'slug' => 'china'],
            ['id' => 9, 'name' => 'Germany', 'slug' => 'germany'],
            ['id' => 10, 'name' => 'Turkey', 'slug' => 'turkey'],
            ['id' => 11, 'name' => 'Colombia', 'slug' => 'colombia'],
            ['id' => 12, 'name' => 'United States', 'slug' => 'united-states'],
            ['id' => 13, 'name' => 'Bulgaria', 'slug' => 'bulgaria'],
            ['id' => 14, 'name' => 'Romania', 'slug' => 'romania'],
            ['id' => 15, 'name' => 'Hungary', 'slug' => 'hungary'],
            ['id' => 16, 'name' => 'Egypt', 'slug' => 'egypt'],
            ['id' => 17, 'name' => 'France', 'slug' => 'france'],
            ['id' => 18, 'name' => 'South Africa', 'slug' => 'south africa'],
            ['id' => 19, 'name' => 'United Arab Emirates', 'slug' => 'uae'],
            ['id' => 20, 'name' => 'Ireland', 'slug' => 'ireland'],
            ['id' => 21, 'name' => 'Croatia', 'slug' => 'croatia'],
            ['id' => 22, 'name' => 'Italy', 'slug' => 'italy'],
            ['id' => 23, 'name' => 'Switzerland', 'slug' => 'switzerland'],
            ['id' => 24, 'name' => 'Finland', 'slug' => 'finland'],
            ['id' => 25, 'name' => 'Malaysia', 'slug' => 'malaysia'],
            ['id' => 26, 'name' => 'Kuwait', 'slug' => 'kuwait'],
            ['id' => 27, 'name' => 'Japan', 'slug' => 'japan'],
            ['id' => 28, 'name' => 'Peru', 'slug' => 'peru'],
            ['id' => 29, 'name' => 'Portugal', 'slug' => 'portugal'],
            ['id' => 30, 'name' => 'Slovenia', 'slug' => 'slovenia'],
            ['id' => 32, 'name' => 'Luxembourg', 'slug' => 'luxembourg'],
            ['id' => 33, 'name' => 'Malta', 'slug' => 'malta'],
            ['id' => 34, 'name' => 'Bahrain', 'slug' => 'bahrain'],
            ['id' => 35, 'name' => 'Australia', 'slug' => 'australia'],
            ['id' => 36, 'name' => 'Mexico', 'slug' => 'mexico'],
            ['id' => 37, 'name' => 'Monaco', 'slug' => 'monaco'],
            ['id' => 38, 'name' => 'Russia', 'slug' => 'russia'],
            ['id' => 39, 'name' => 'India', 'slug' => 'india'],
            ['id' => 40, 'name' => 'Norway', 'slug' => 'norway'],
            ['id' => 41, 'name' => 'Montenegro', 'slug' => 'montenegro'],
            ['id' => 42, 'name' => 'Czech Republic', 'slug' => 'czech-republic'],
            ['id' => 43, 'name' => 'Latvia', 'slug' => 'latvia'],
            ['id' => 44, 'name' => 'Brazil', 'slug' => 'brazil'],
            ['id' => 45, 'name' => 'South Korea', 'slug' => 'south-korea'],
            ['id' => 46, 'name' => 'Singapore', 'slug' => 'singapore'],
            ['id' => 47, 'name' => 'Saint Barthelemy', 'slug' => 'saint-barthelemy'],
            ['id' => 48, 'name' => 'Sweden', 'slug' => 'sweden'],
            ['id' => 49, 'name' => 'Taiwan', 'slug' => 'taiwan'],
            ['id' => 50, 'name' => 'Estonia', 'slug' => 'estonia'],
            ['id' => 51, 'name' => 'Canada', 'slug' => 'canada'],
            ['id' => 52, 'name' => 'Austria', 'slug' => 'austria'],
            ['id' => 53, 'name' => 'Poland', 'slug' => 'poland'],
            ['id' => 54, 'name' => 'New Zealand', 'slug' => 'new-zealand'],
            ['id' => 55, 'name' => 'Albania', 'slug' => 'albania'],
            ['id' => 56, 'name' => 'Armenia', 'slug' => 'armenia'],
            ['id' => 57, 'name' => 'Argentina', 'slug' => 'argentina'],
            ['id' => 59, 'name' => 'Tanzania', 'slug' => 'tanzania'],
            ['id' => 60, 'name' => 'Belarus', 'slug' => 'belarus'],
            ['id' => 61, 'name' => 'Bosnia Herzegovina', 'slug' => 'bosnia-herzegovina'],
            ['id' => 62, 'name' => 'Cyprus', 'slug' => 'cyprus'],
            ['id' => 63, 'name' => 'Denmark', 'slug' => 'denmark'],
            ['id' => 64, 'name' => 'Iceland', 'slug' => 'iceland'],
            ['id' => 65, 'name' => 'Liechtenstein', 'slug' => 'liechtenstein'],
            ['id' => 66, 'name' => 'Lithuania', 'slug' => 'lithuania'],
            ['id' => 67, 'name' => 'Moldova', 'slug' => 'moldova'],
            ['id' => 68, 'name' => 'Macedonia', 'slug' => 'macedonia'],
            ['id' => 69, 'name' => 'Serbia', 'slug' => 'serbia'],
            ['id' => 70, 'name' => 'Slovakia', 'slug' => 'slovakia'],
            ['id' => 71, 'name' => 'United Kingdom', 'slug' => 'united-kingdom'],
            ['id' => 72, 'name' => 'Chile', 'slug' => 'chile'],
            ['id' => 73, 'name' => 'Costarica', 'slug' => 'costarica'],
            ['id' => 74, 'name' => 'Ecuador', 'slug' => 'ecuador'],
            ['id' => 75, 'name' => 'French Polynesia', 'slug' => 'french-polynesia'],
            ['id' => 76, 'name' => 'Georgia', 'slug' => 'georgia'],
            ['id' => 77, 'name' => 'Ghana', 'slug' => 'ghana'],
            ['id' => 78, 'name' => 'Guatemala', 'slug' => 'guatemala'],
            ['id' => 79, 'name' => 'Israel', 'slug' => 'israel'],
            ['id' => 80, 'name' => 'Jamaica', 'slug' => 'jamaica'],
            ['id' => 81, 'name' => 'Jordan', 'slug' => 'jordan'],
            ['id' => 82, 'name' => 'Kazakhstan', 'slug' => 'kazakhstan'],
            ['id' => 83, 'name' => 'Kenya', 'slug' => 'kenya'],
            ['id' => 84, 'name' => 'Lebanon', 'slug' => 'lebanon'],
            ['id' => 85, 'name' => 'Morocco', 'slug' => 'morocco'],
            ['id' => 86, 'name' => 'Nigeria', 'slug' => 'nigeria'],
            ['id' => 87, 'name' => 'Oman', 'slug' => 'oman'],
            ['id' => 88, 'name' => 'Pakistan', 'slug' => 'pakistan'],
            ['id' => 89, 'name' => 'Panama', 'slug' => 'panama'],
            ['id' => 90, 'name' => 'Philippines', 'slug' => 'philippines'],
            ['id' => 91, 'name' => 'Qatar', 'slug' => 'qatar'],
            ['id' => 92, 'name' => 'Saudi Arabia', 'slug' => 'saudi-arabia'],
            ['id' => 93, 'name' => 'Sri Lanka', 'slug' => 'sri-lanka'],
            ['id' => 94, 'name' => 'Tunisia', 'slug' => 'tunisia'],
            ['id' => 95, 'name' => 'Uruguay', 'slug' => 'uruguay'],
            ['id' => 96, 'name' => 'Uzbekistan', 'slug' => 'uzbekistan'],
            ['id' => 97, 'name' => 'Venezuela', 'slug' => 'venezuela'],
            ['id' => 98, 'name' => 'Vietnam', 'slug' => 'vietnam'],
            ['id' => 99, 'name' => 'Dominican Republic', 'slug' => 'dominican-republic'],
            ['id' => 100, 'name' => 'Bahamas', 'slug' => 'bahamas'],
            ['id' => 101, 'name' => 'Barbados', 'slug' => 'barbados'],
            ['id' => 102, 'name' => 'Puerto Rico', 'slug' => 'puerto-rico'],
            ['id' => 103, 'name' => 'Turks and Caicos', 'slug' => 'turks-and-caicos'],
            ['id' => 104, 'name' => 'Saint Tropez', 'slug' => 'saint-tropez'],
        ]);
        
    }
}
